CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "lastname" varchar(20) NOT NULL,
  "email" varchar(20) NOT NULL,
  "password" varchar(8) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "users_id" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "url" varchar(200) NOT NULL,
  "roles_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "course_video_id" int NOT NULL
);

CREATE TABLE "pivote_courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categories_id" int NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "description" varchar(200) NOT NULL,
  "level_id" int NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(30) NOT NULL
);

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "level" ("level");

ALTER TABLE "roles" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("course_video_id") REFERENCES "course_video" ("id");

INSERT INTO users (id, name, lastname, email, password, age)
list-# VALUES
list-#   (1, 'Anderson', 'Duran', 'anderson@gmail.com', 'user1234', 22),
list-#   (2, 'Carlos', 'Gomez', 'carlos@gmail.com', 'user1234', 21),
list-#   (3, 'Magalis', 'Lopez', 'magalis@gmail.com', 'user1234', 26);

list=# INSERT INTO roles (name, users_id) VALUES
list-# ('Student', 1),
list-# ('Teacher', 3),
list-# ('Admin', 2);

list=# INSERT INTO course_video (title, url, roles_id) VALUES
list-# ('HTML', 'https://node/semana1', 1),
list-# ('Data Base', 'https://node/semana8', 1);

list=# INSERT INTO categories (name, course_video_id) VALUES
list-# ('Backend', 2),
list-# ('Frontend', 1);

list=# INSERT INTO level (level) VALUES
list-# ('Beginners'),
list-# ('Intermediate'),
list-# ('Advanced');

list=# INSERT INTO courses (title, description, level_id, teacher) VALUES
list-# ('Fundamentals', 'Basics of HTML, CSS and JavaScript.', 1, 3),
list-# ('Node.js', 'Database design', 2, 3);

list=# INSERT INTO pivote_courses_categories (categories_id, courses_id) VALUES
list-# (2, 1),
list-# (1, 2);









